#!/bin/bash
# Submit a whole stage as a Slurm job array, after printing the text that must be
# committed to FINDINGS.md first.
#
#   ./submit_stage.sh 0                      # noise floor, all three node tiers
#   ./submit_stage.sh 1                      # knob verification, 2 nodes, INFO logging
#   ./submit_stage.sh 2                      # PB-20 screen, 3 replicates x 2 blocks
#   ./submit_stage.sh 3a                     # algo x proto grid
#   CONFIRM=1 ./submit_stage.sh 0            # actually submit
#
# Without CONFIRM=1 it prints the plan and submits nothing. That is the default on
# purpose: the pre-registration has to be in the repo before the data exists, or
# the thresholds can be adjusted after the fact and the whole study is worth less.
#
# An array rather than serial resubmission, because array members queue together
# and land on whatever the scheduler hands out. Resubmitting one at a time
# correlates node placement with time of day, and placement is the largest noise
# term in the whole study.

set -euo pipefail

STAGE="${1:-}"
[ -n "${STAGE}" ] || { echo "usage: $0 <stage>   (0, 1, 2, 3a, 3b)" >&2; exit 2; }

SEED="${SEED:-0}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${HERE}/../.." && pwd)"
ACCOUNT="${ACCOUNT:-project_462000131}"

# Partition is pinned per stage and never mixed within one: dev-g and standard-g
# have different node populations and different queue dynamics, and a stage split
# across both has partition as an uncontrolled factor.
# Stage 0 runs entirely on standard-g even though dev-g would take 8 nodes (its
# MaxNodes is 32). The noise floor has to characterise the partition the real
# measurements happen in: an MDE estimated on dev-g and applied to standard-g
# results would be describing a different node population and a different set of
# neighbours. Stage 1 stays on dev-g because it is a verification pass, not a
# timing measurement, so partition cannot confound it.
case "${STAGE}" in
  0)  TIERS=("2 3 standard-g 01:00:00" "4 5 standard-g 01:00:00" "8 2 standard-g 00:50:00"); BLOCKS=1 ;;
  1)  TIERS=("2 2 dev-g 01:30:00"); BLOCKS=1 ;;
  2)  TIERS=("4 3 standard-g 01:00:00"); BLOCKS=2 ;;
  3a) TIERS=("4 3 standard-g 00:50:00"); BLOCKS=1 ;;
  3b) TIERS=("4 3 standard-g 00:50:00"); BLOCKS=1 ;;
  *)  echo "unknown stage ${STAGE}" >&2; exit 2 ;;
esac

echo "=============================================================="
echo " PRE-REGISTRATION — paste into FINDINGS.md and commit BEFORE"
echo " submitting. After this point no threshold may be changed in"
echo " light of the data."
echo "=============================================================="
echo
echo "## Stage ${STAGE} pre-registration"
echo
echo "- Submitted: $(date -u +%Y-%m-%dT%H:%M:%SZ) by ${USER}"
echo "- Seed: ${SEED}    Account: ${ACCOUNT}"
echo "- Repo commit: $(git -C "${REPO}" rev-parse --short HEAD 2>/dev/null || echo unknown)"
echo "- Design generated by \`designs.py\`, reproducible from (stage, replicate, seed)."
echo
echo "| tier | nodes | allocations | blocks each | partition | walltime |"
echo "| --- | --- | --- | --- | --- | --- |"
total=0
for tier in "${TIERS[@]}"; do
  read -r nodes reps partition walltime <<<"${tier}"
  echo "| ${nodes}-node | ${nodes} | ${reps} | ${BLOCKS} | \`${partition}\` | ${walltime} |"
  total=$(( total + reps * BLOCKS ))
done
echo
echo "- Total allocations this stage: **${total}**"
echo
echo "### Thresholds, fixed now"
echo
echo "| observed paired effect on the promotion scalar | verdict |"
echo "| --- | --- |"
echo "| >= +5%, interval excludes 0, consistent sign in >= 3 allocations | promote |"
echo "| +3% to +5% | hold — retest only in combination at Stage 4 |"
echo "| abs < 3%, CI half-width < 3% | confidently inert — ship commented out |"
echo "| abs < 3%, CI half-width >= 3% | underpowered — no verdict |"
echo "| <= -5% | kill — into the DO NOT SET section |"
echo
echo "- 3% floor is hard regardless of significance. Multiplicity: Benjamini-Hochberg, q = 0.10."
echo "- Sentinel gate: discard and resubmit any allocation with |log(S'/S)| > 3 sigma_pos."
echo "- Sham must not reach 3%, or every positive in this stage is suspect."
echo "- \`cap4\` must come back strongly negative, or the harness is not reaching the ranks."
echo "- A knob whose \`knob_verified\` is false carries no verdict, only UNVERIFIED."
echo

if [ "${STAGE}" = "0" ]; then
  echo "### What Stage 0 decides"
  echo
  echo "Everything after it. It reports CV_alloc, CV_pos, the position slope fitted on"
  echo "slots 2+, the slot-1 step estimated separately, and the MDE ladder. The rest of"
  echo "the study is sized from that MDE and not before."
  echo
fi

echo "=============================================================="
if [ "${CONFIRM:-0}" != "1" ]; then
  echo "Dry run. Nothing submitted. Re-run with CONFIRM=1 once the block above is committed."
  exit 0
fi

# Untracked files are ignored on purpose: Slurm drops .out/.err into the repo root
# and they are not part of the commit the pre-registration names. Modified *tracked*
# files are the real hazard, because then the recorded commit does not describe the
# code that is about to run.
if [ -n "$(git -C "${REPO}" status --porcelain --untracked-files=no 2>/dev/null)" ]; then
  echo "WARNING: the working tree is dirty, so the recorded commit does not describe" >&2
  echo "         the code that is about to run. Commit first." >&2
  exit 1
fi

# Staleness is as bad as dirtiness and much easier to miss. A `git fetch && git reset`
# that fails on the fetch leaves the checkout silently behind, and the stage then runs
# old code under a pre-registration naming a commit it never used. That happened once:
# arrays 22119621/22119622 launched three commits behind and had to be cancelled.
BRANCH="$(git -C "${REPO}" rev-parse --abbrev-ref HEAD 2>/dev/null)"
if ! git -C "${REPO}" fetch -q origin "${BRANCH}" 2>/dev/null; then
  echo "WARNING: could not reach origin to check for staleness. Refusing to submit" >&2
  echo "         rather than risk running code the pre-registration does not name." >&2
  exit 1
fi
LOCAL_HEAD="$(git -C "${REPO}" rev-parse HEAD)"
REMOTE_HEAD="$(git -C "${REPO}" rev-parse FETCH_HEAD)"
if [ "${LOCAL_HEAD}" != "${REMOTE_HEAD}" ]; then
  echo "WARNING: this checkout is not origin/${BRANCH}." >&2
  echo "         local  ${LOCAL_HEAD}" >&2
  echo "         origin ${REMOTE_HEAD}" >&2
  echo "         Reset to origin before submitting; the pre-registration names a commit." >&2
  exit 1
fi

for tier in "${TIERS[@]}"; do
  read -r nodes reps partition walltime <<<"${tier}"
  for block in $(seq 1 "${BLOCKS}"); do
    extra=()
    # Stage 1 asserts, it does not time, so it runs a minimal grid with INFO logging
    # on. INFO from every rank would contaminate a timing measurement, which is
    # exactly why this is a separate stage.
    [ "${STAGE}" = "1" ] && extra+=(--export=ALL,SLOT_DEBUG=1,PROFILE_ARGS=--verify-only,SLOT_TIMEOUT_MIN=4)
    jobid=$(STAGE="${STAGE}" BLOCK="${block}" SEED="${SEED}" REPO_DIR="${REPO}" \
      sbatch --parsable \
        --account="${ACCOUNT}" --partition="${partition}" \
        --nodes="${nodes}" --time="${walltime}" \
        --array="1-${reps}" \
        --job-name="rccl-tune-s${STAGE}b${block}-n${nodes}" \
        "${extra[@]}" \
        "${HERE}/run_block.sh")
    echo "submitted stage ${STAGE} block ${block} at ${nodes} nodes on ${partition}: array ${jobid}"
  done
done

echo
echo "Record these array ids in FINDINGS.md next to the pre-registration block."
